# Data Preprocessing

## Dealing with missing data

In [2]:
import pandas as pd
from io import StringIO

In [3]:
csv_data=\
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.1,11.0,12.0,'''

In [5]:
df=pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.1  11.0  12.0  NaN

In [13]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [15]:
df.values #-> gives us numpy array

array([[  1. ,   2. ,   3. ,   4. ],
       [  5. ,   6. ,   nan,   8. ],
       [ 10.1,  11. ,  12. ,   nan]])

In [17]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.1  11.0

In [19]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [20]:
df.dropna(how='all')

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.1  11.0  12.0  NaN

In [25]:
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [26]:
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.1  11.0  12.0  NaN

In [40]:
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN', strategy='mean',axis=0)
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[  1. ,   2. ,   3. ,   4. ],
       [  5. ,   6. ,   7.5,   8. ],
       [ 10.1,  11. ,  12. ,   6. ]])

In [75]:
df = pd.DataFrame([['green','M',10.1,'class1'],['red','L',13.5,'class2']
                  ,['blue','XL',15.3,'class1']])
df.columns = ['color','size','price','classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [72]:
size_mapping = {'XL':3,'L':2,'M':1}
df['size']=df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [73]:
import numpy as np
class_mapping = {label:idx for idx,label in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [74]:
df['classlabel']=df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [76]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([0, 1, 0])

In [77]:
class_le.inverse_transform(y)

array(['class1', 'class2', 'class1'], dtype=object)