##  Introduction
* Multidimensional Homogenous array
* Dimensions - Axes 
* No. of axis - Rank


In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
print str(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.size

15

In [10]:
a.dtype

dtype('int64')

In [11]:
a.itemsize

8

In [15]:
a.data

<read-write buffer for 0x7fabb83b7a30, size 120, offset 0 at 0x7fabc114afb0>

In [16]:
type(a)

numpy.ndarray

In [17]:
b = np.array([1,2,3,4,5])
type(b)

numpy.ndarray

## Array Creation

In [18]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
a.dtype

dtype('int64')

In [20]:
b=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]).reshape(3,2)
b.dtype

dtype('float64')

<div class="alert alert-block alert-info">python a = np.array(1,2,3,4) is incorrect as np.array requires a single list and not multiple numeric argument</div>