##  Introduction
* Multidimensional Homogenous array
* Dimensions - Axes 
* No. of axis - Rank


In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
print str(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.size

15

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

<read-write buffer for 0x7f45953eb3f0, size 120, offset 0 at 0x7f45904fc170>

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([1,2,3,4,5])
type(b)

numpy.ndarray

## Array Creation

In [11]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
a.dtype

dtype('int64')

In [12]:
b=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]).reshape(3,2)
b.dtype

dtype('float64')


<div class="alert alert-block alert-info">python a = np.array(1,2,3,4) is incorrect as np.array requires a single list and not multiple numeric argument</div>

In [13]:
c = np.array([[1,2],[3,4]],dtype="complex")
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

<div class="alert alert-block alert-info"> By default, the dtype of the created array is float64.(when ones,zeros and empty arrays are created)</div>

In [14]:
np.zeros((2,2,2))

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [18]:
np.arange(0.2,0.8,0.2)

array([ 0.2,  0.4,  0.6,  0.8])

In [19]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [20]:
x=np.linspace(0,2*np.pi,100)

In [21]:
np.sin(x)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [22]:
np.random.rand(2,3)

array([[ 0.58564942,  0.57462259,  0.21660162],
       [ 0.59876533,  0.4537075 ,  0.94924243]])

In [23]:
np.random.randn(2,3)

array([[-1.27011836, -0.14503474,  0.88293037],
       [ 0.19825921, -1.72684738,  0.37748043]])

In [24]:
y = np.arange(1000).reshape(10,100)

### Basic Operations 

Arithmetic operations on numpy arrays apply _elementwise_.

In [33]:
a = np.arange(5)
b = np.array([2,5,1,7,1])

In [34]:
a-b

array([-2, -4,  1, -4,  3])

In [35]:
a*b  #ELEMENTWISE PRODUCT

array([ 0,  5,  2, 21,  4])

In [36]:
a<b

array([ True,  True, False,  True, False], dtype=bool)

In [37]:
a.dot(b) #MATRIX PRODUCT
np.dot(a,b)

32

In [39]:
a.sum()

10

In [40]:
a.min()

0

In [41]:
a.max()

4

In [42]:
c = np.arange(12).reshape(3,4)

In [43]:
print c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
c.min(axis=1)

array([0, 4, 8])

In [48]:
c.sum(axis=1)

array([ 6, 22, 38])

In [51]:
c.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

### Universal functions

In [53]:
import numpy as np
x = np.arange(13)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
np.exp(x)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05])

In [55]:
np.sqrt(x)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162])

In [56]:
np.add(x,x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

Other functions -all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

### Indexing, Slicing and Iterating

In [57]:
import numpy as np
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
x[2:5]

array([2, 3, 4])

In [62]:
x[:6:2]=-33
x

array([-33,   1, -33,   3, -33,   5,   6,   7,   8,   9,  10,  11])

In [70]:
x[::-1]

array([ 11,  10,   9,   8,   7,   6,   5, -33,   3, -33,   1, -33])

In [74]:
for i in x:
    print i**2

1089
1
1089
9
1089
25
36
49
64
81
100
121


In [76]:
def func(x,y):
    return 10*x+y
b = np.fromfunction(func,(5,3),dtype="int")
b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [84]:
b[0:5,2]

array([ 2, 12, 22, 32, 42])

In [86]:
b[...,1]

array([ 1, 11, 21, 31, 41])

In [87]:
for i in b:
    print i

[0 1 2]
[10 11 12]
[20 21 22]
[30 31 32]
[40 41 42]


In [88]:
for i in b.flat:
    print i

0
1
2
10
11
12
20
21
22
30
31
32
40
41
42


### Shape Manipulation

In [91]:
import numpy as np
a = np.random.randint(1,100,(5,4,3))
a

array([[[91,  8, 67],
        [87,  2, 39],
        [71, 15, 52],
        [16, 50, 22]],

       [[97, 75, 67],
        [24, 44, 55],
        [ 6, 10,  2],
        [30, 10, 65]],

       [[52,  9, 26],
        [91, 89, 64],
        [ 9, 66, 71],
        [75, 74, 78]],

       [[12, 40, 60],
        [53, 45,  7],
        [23, 77,  5],
        [27, 27,  8]],

       [[64, 28, 54],
        [25, 11, 34],
        [54, 59, 46],
        [ 4,  3, 48]]])

In [93]:
a.ravel()  ## Flattens array

array([91,  8, 67, 87,  2, 39, 71, 15, 52, 16, 50, 22, 97, 75, 67, 24, 44,
       55,  6, 10,  2, 30, 10, 65, 52,  9, 26, 91, 89, 64,  9, 66, 71, 75,
       74, 78, 12, 40, 60, 53, 45,  7, 23, 77,  5, 27, 27,  8, 64, 28, 54,
       25, 11, 34, 54, 59, 46,  4,  3, 48])

In [94]:
a.reshape(3,4,5)

array([[[91,  8, 67, 87,  2],
        [39, 71, 15, 52, 16],
        [50, 22, 97, 75, 67],
        [24, 44, 55,  6, 10]],

       [[ 2, 30, 10, 65, 52],
        [ 9, 26, 91, 89, 64],
        [ 9, 66, 71, 75, 74],
        [78, 12, 40, 60, 53]],

       [[45,  7, 23, 77,  5],
        [27, 27,  8, 64, 28],
        [54, 25, 11, 34, 54],
        [59, 46,  4,  3, 48]]])

In [96]:
a.T ## Transpose

array([[[91, 97, 52, 12, 64],
        [87, 24, 91, 53, 25],
        [71,  6,  9, 23, 54],
        [16, 30, 75, 27,  4]],

       [[ 8, 75,  9, 40, 28],
        [ 2, 44, 89, 45, 11],
        [15, 10, 66, 77, 59],
        [50, 10, 74, 27,  3]],

       [[67, 67, 26, 60, 54],
        [39, 55, 64,  7, 34],
        [52,  2, 71,  5, 46],
        [22, 65, 78,  8, 48]]])

In [97]:
a.T.shape

(3, 4, 5)

In [99]:
a.reshape(3,-1,4)

array([[[91,  8, 67, 87],
        [ 2, 39, 71, 15],
        [52, 16, 50, 22],
        [97, 75, 67, 24],
        [44, 55,  6, 10]],

       [[ 2, 30, 10, 65],
        [52,  9, 26, 91],
        [89, 64,  9, 66],
        [71, 75, 74, 78],
        [12, 40, 60, 53]],

       [[45,  7, 23, 77],
        [ 5, 27, 27,  8],
        [64, 28, 54, 25],
        [11, 34, 54, 59],
        [46,  4,  3, 48]]])

### Stacking together different arrays

In [104]:
import numpy as np
a = np.random.randint(1,100,(2,2,2))
b = np.random.randint(1,100,(2,2,2))
print a 
print b

[[[48 81]
  [93 22]]

 [[56 30]
  [42  4]]]
[[[38 96]
  [86 34]]

 [[16 98]
  [80 73]]]


In [105]:
np.vstack((a,b))

array([[[48, 81],
        [93, 22]],

       [[56, 30],
        [42,  4]],

       [[38, 96],
        [86, 34]],

       [[16, 98],
        [80, 73]]])

In [106]:
np.hstack((a,b))

array([[[48, 81],
        [93, 22],
        [38, 96],
        [86, 34]],

       [[56, 30],
        [42,  4],
        [16, 98],
        [80, 73]]])

In [107]:
np.column_stack((a,b))

array([[[48, 81],
        [93, 22],
        [38, 96],
        [86, 34]],

       [[56, 30],
        [42,  4],
        [16, 98],
        [80, 73]]])

In [109]:
np.hsplit(a,2)

[array([[[48, 81]],
 
        [[56, 30]]]), array([[[93, 22]],
 
        [[42,  4]]])]

### Copies and Views

#### Shallow Copy

In [112]:
import numpy as np
a=np.random.randint(1,10,(3,5))
b=a

In [113]:
b is a ## b and a are the same

True

In [115]:
b.shape= 5,3
a.shape

(5, 3)

<div class="alert alert-box alert-info">Python passes mutable objects as references, so function calls make no copy.</div>

In [116]:
def f(x):
    print id(x)
    return
id(a)

139936611404816

In [117]:
f(a)

139936611404816


#### View or Shallow Copy

In [119]:
c= a.view() # returns a view of a 
c is a 

False

In [123]:
c.base is a

True

In [122]:
c.shape=3,5
a.shape  # no change in shape

(5, 3)

In [131]:
c[0,4]=999
a

array([[  5,   9, 999],
       [  8, 999,   8],
       [  7,   9,   3],
       [  8,   7,   7],
       [  8,   1,   1]])

In [133]:
s = a[1:3,:]
s[:]=-69
a

array([[  5,   9, 999],
       [-69, -69, -69],
       [-69, -69, -69],
       [  8,   7,   7],
       [  8,   1,   1]])

#### Deep Copy

In [135]:
x = a.copy()
x is a 

False

In [136]:
x.base is a

False

In [137]:
x[0,0]=1234
a[0,0]

5